### ISSUE TITLE
Reincarnation (level 74) 任务坐标错误

### ISSUE THREAD

**Issue by zhuzhuOwO** [EternityTQ/WynncraftCNguide#29]
baab's wool(baab位于maro peaks[238 7 -3975]
从[-181 58 -4060]的洞口下去，走到底后左拐)

**Comment by zhuzhuOwO** [comment]
应更正为
baab's wool(baab位于maro peaks[238 7 -3975]
从[181 58 -4060]的洞口下去，走到底后左拐)

**Comment by EternityTQ** [comment]
solved

**Comment by zhuzhuOwO** [comment]
另外建议在此小节提示玩家带上"ice nation"任务中 给的 "Climbing Helmet"
（我就是跑到这里发现没戴头盔，又回去取了一趟）
ps:大佬维护wiki辛苦了
